# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Units-PhysicalValue
version:      0.38
version_from: PhysicalValue.pm
installdirs:  site
requires:
    Math::Algebra::Symbols:        0
    Math::Units:                   0
    Number::Format:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
